### ISSUE TITLE
Fail to import 'ClassificationOptions' from 'ibm_watson.natural_language_understanding_v1' in py3.7

### ISSUE THREAD

**Issue by Fred-Fan** [watson-developer-cloud/python-sdk#827]
Remember, an issue is not the place to ask questions. If you have issues with the APIs or have a question about the Watson services, see [Stack Overflow](https://stackoverflow.com/questions/tagged/ibm-watson+python).

Before you open an issue, please check if a similar issue already exists or has been closed before.

 **Check service status**

1.  For service issues or 5xx errors, first, go to the [IBM Cloud status page](https://cloud.ibm.com/status?component=compare-comply%2Cdiscovery%2Cconversation%2Cwatson-vision-combined%2Cnatural-language-understanding%2Cnatural-language-classifier%2Clanguage-translator%2Cpersonality-insights%2Cspeech-to-text%2Ctext-to-speech%2Ctone-analyzer&selected=status) and check the status of the service.
1.  If the service status is OK, continue with a bug report.

 ---

**Overview**
I am trying the APIs for NLU using ibm_watson. However, the below import works in python 3.9 but failed in python 3.7
```
from ibm_watson.natural_language_understanding_v1 import ClassificationOptions
```

**Expected behavior**
The component can be imported successfully

**Actual behavior**
I got an error below:
```
Python 3.7.12 (default, Mar 23 2022, 17:57:27) 
[Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_watson
>>> ibm_watson.__version__
'6.1.0'
>>> from ibm_watson.natural_language_understanding_v1 import ClassificationOptions
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ClassificationOptions' from 'ibm_watson.natural_language_understanding_v1' (/Users/xuanchengfan/.pyenv/versions/3.7.12/lib/python3.7/site-packages/ibm_watson/natural_language_understanding_v1.py)
>>> 
```

**How to reproduce**
```
import ibm_watson
from ibm_watson.natural_language_understanding_v1 import ClassificationOptions
```

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**SDK Version**
'6.1.0'

**Additional information:**
- OS: macOS 13.0.1 
- Which version of `Python` are you using? 3.7

**Additional context**
my IBM email: xuancheng.fan@ibm.com
